enum ResponseCode {
    //HTTP Status 200
    SUCCESS = "SUCESS",

    //HTTP Status 400
    VALIDATION_FAILED = "VALIDATION FAILED",
    NOT_EXISTED_USER = "NOT EXISTED USER",
    DUPLICATE_STUDENT_ID = "DUPLICATE STUDENT_ID",
    DUPLICATE_STUDENT_EMAIL = "DUPLICATE STUDENT_EMAIL",
    DUPLICATE_STUDENT_PHONE_NUMBER = "DUPLICATE STUDENT_PHONE_NUMBER",
    DUPLICATE_EMPLOYEE_ID = "DUPLICATE EMPLOYEE_ID",
    DUPLICATE_EMPLOYEE_EMAIL = "DUPLICATE EMPLOYEE_EMAIL",
    DUPLICATE_EMPLOYEE_PHONE_NUMBER = "DUPLICATE EMPLOYEE_PHONE_NUMBER",

    //HTTP Status 401
    SIGN_IN_FAIL = "SIGN IN FAIL",
    AUTHORIZATION_FAIL = "AUTHORIZATION FAIL",

    //HTTP Status 403
    NO_PERMISSION = "NO PERMISSION",

    //HTTP Status 500
    DATABASE_ERROR = "DATABASE ERROR",
}

export default ResponseCode;